apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-everything
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-everything
  template:
    metadata:
      labels:
        app: mcp-everything
    spec:
      containers:
        - name: mcp-everything
          image: chuangw/mcp-everything:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-everything-svc
spec:
  type: ClusterIP
  selector:
    app: mcp-everything
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
